### ISSUE TITLE
Base Table not found

### ISSUE THREAD

**Issue by nettz** [KaanErturk/piwik-SiteUrlTrackingID#1]
After installing the plugin i get the following error message on the Tracking Code Page
Base table or view not found: 1146 Table 'xxxxx.site' doesn't exist

Do i have to setup the Table myself? 

Cheers in Advance

**Comment by AnnaDamm** [comment]
It seems to me, that the plugin does not respect the actual prefix. For me, i am using the prefix "piwik_", so the correct table would be "piwik_site", not the "piwik.site" that it tries to use.

**Comment by KaanErturk** [comment]
Apologies for responding late as I did not get an email and am just seeing this ticket.

You are correct, plugin doesn't use the table prefix and this is not right. I will make the necessary changes and push a new version.

Thanks for reporting this.

**Comment by KaanErturk** [comment]
@nettz @Arany 

https://github.com/KaanErturk/piwik-SiteUrlTrackingID/commit/7af8e90beeaf67bb0487e40221db6ad77ff4f69b fixes the issue. Pushed to Piwik Marketplace as well, can be updated now.

Thanks again for reporting the issue.
